### ISSUE TITLE
translate arrays-and-slices.md

### ISSUE THREAD

**Issue by dolsup** [Gunforge/learn-go-with-tests-ko#15]
Anyone can get this job. Assign yourself to this issue.

**Comment by yoongun** [comment]
This one is super long. It'll take a week or two for someone who takes it. We can consider dividing this file into two and work separately.

**Comment by dolsup** [comment]
It seems not to be so long, excluding code snippets.

**Comment by yoongun** [comment]
Ah, I see. Anyway, I'm not taking it for now.

**Comment by yoongun** [comment]
I'll take this for next.

**Comment by yoongun** [comment]
Done with PR #48
