### ISSUE TITLE
Suggestion on the branch naming convention

### ISSUE THREAD

**Issue by yoongun** [Gunforge/learn-go-with-tests-ko#2]
I want to propose the naming convention of the translation branches as

`trans/<filename>`

By dividing branches this way, we can work simultaneously without confliction between the process.

**Comment by yoongun** [comment]
Because we are in plan to do revision after the draft, make two kinds of the branch instead. Like:
`trans/<filename>` and `draft/<filename>`
First, I'll create a draft on `draft/<filename>`. Then you can choose to improve a draft by adding translation which is undone or clean the language by pulls down a draft to the trans branch.

**Comment by dolsup** [comment]
it sounds great.

I'll rename `readme` branch which I already made to `draft/readme`.
