### ISSUE TITLE
한국어 번역 문체에 대한 제안

### ISSUE THREAD

**Issue by dolsup** [Gunforge/learn-go-with-tests-ko#3]
다수의 기여자가 작업하고 있기 때문에 문체에 대해 통일된 가이드가 있어야 합니다.

4가지 정도의 선택지가 있는 것으로 보입니다.
1. 하십시오체만 사용: https://docs.microsoft.com/ko-kr/previous-versions/msdn10/gg190737(v=msdn.10)
2. 해요체만 사용: _예시를 찾지 못함_
3. 하십시오체를 기본으로 해요체 혼용: https://developer.android.com/guide?hl=ko
4. 해요체를 기본으로 하십시오체 혼용: https://rogerdudler.github.io/git-guide/index.ko.html
5. 평어체: https://github.com/golangkorea/effective-go/blob/master/concurrency.md

저는 하십시오체를 기본으로 해요체를 혼용하는 것이 최근 주류적인 작성법이라고 생각해서 3번을 제안합니다. (수치적 근거는 없습니다.)

다음은 하십시오체를 기본으로 해요체를 혼용하는 것에 대한 국립국어원의 의견입니다.
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=121124

다음은 하십시오와 해요체 혼용 현상에 대한 분석입니다.
http://www.hani.co.kr/arti/society/schooling/284353.html

**Comment by yoongun** [comment]
국립 국어원의 답변을 본 결과, 해요체는 격식체인 '하오체'와 '합쇼체'의 비격식체라고 되어 있습니다. 

3번에 달아주신 참조 링크의 경우에는 합니다체와 해요체를 혼용하고 있지만, 국립 국어원에서 합니다체를 사용해야 하는 경우에는 격식체인 합쇼체를 사용할 것을 권장하고 있기 때문에 3번의 경우 '합니다체를 기본으로 합쇼체 혼용'으로 수정하는 편이 더 바람직하다고 생각합니다.

**Comment by dolsup** [comment]
제가 단어를 잘못 사용했는데 합니다체 -> 하십시오체입니다. 합니다체는 없습니다.

**Comment by yoongun** [comment]
아, 그렇군요. 그럼 합쇼체 + 해요체 의 혼용이군요.

이 이슈는 트위터에서 진행중인 투표 결과를 확인 할 수 있는 내일 이후에 더 진행하도록 합시다.

**Comment by roomedia** [comment]
문맥에 따라 합쇼체를 쓸지 해요체를 쓸지 고민하기보다 합쇼체나 해요체만 사용하는 게 덜 소모적이지 않을까요?

**Comment by yoongun** [comment]
번역 인원이 많아지면 확실히 한쪽으로 통일하는 편이 좋겠습니다.

하지만 현시점으로서는 어느 쪽 하나만을 고수하기에는 문장이 부자연 스러워 지는 경우가 존재하여, 어느 정도의 혼용은 불가피 하다고 생각하고 있습니다.

**Comment by dolsup** [comment]
혼용할 때 명령형과 의문형만 해요체로 대체하는 건 어떨까요?
예)
- 설치하십시오. -> 설치하세요.
- 확인하셨습니까? -> 확인하셨나요?

**Comment by yoongun** [comment]
저는 괜찮다고 생각합니다. 이렇게 해서 문제가 생겼을떄 추가적인 예외 조항을 명시하는 방향으로 가죠.

**Comment by roomedia** [comment]
agree

**Comment by yoongun** [comment]
하십시오체를 기본으로 예외적 경우에 해요체를 사용하는 것으로 정해졌습니다. 추후 변경사항이 있는 경우 다시 열겠지만 현 시점에서 일단 이슈 닫겠습니다.
