### ISSUE TITLE
Translate Structs, methods & interfaces

### ISSUE THREAD

**Issue by yoongun** [Gunforge/learn-go-with-tests-ko#30]

**Comment by roomedia** [comment]
i'll do that

**Comment by yoongun** [comment]
@EngHyu Please assign yourself from the right panel when you take an issue. Thanks :)

**Comment by yoongun** [comment]
@EngHyu How much have you made your progress?

**Comment by yoongun** [comment]
@EngHyu Please refer to the number of the PR which solved the issue when you close it. Like below
```
#52 has solved the issue. I'll close this issue.
```
