### ISSUE TITLE
Seggestion on commentizing the original text and its format

### ISSUE THREAD

**Issue by dolsup** [Gunforge/learn-go-with-tests-ko#4]
To make revision easier, We should leave the original text with its translated text on drafts.
And I suggest comment it out with HTML comment syntax (`<!-- -->`) because VS Code supports an easy way to comment out markdown text with keyboard shortcut(`cmd + /` or something), and when we make the drafts public, commentized text can be easily removed with a short code or even regex.

**Comment by yoongun** [comment]
I agree

**Comment by roomedia** [comment]
agree

**Comment by yoongun** [comment]
I'll close this issue since the agreement was made.
