### ISSUE TITLE
Can I translate this project in my repo?

### ISSUE THREAD

**Issue by MiryangJung** [Gunforge/learn-go-with-tests-ko#55]
안녕하세요. Hello.

[https://github.com/quii/learn-go-with-tests](https://github.com/quii/learn-go-with-tests) 프로젝트를 번역하려 합니다.

한국어로 번역 중인 이 레포를 발견했으나 번역이 멈춰있는 듯 보여 [제 레포](https://github.com/MiryangJung/learn-go-with-tests-ko) 에서 새로 번역을 시작하려 합니다.

I found this repo that translated into Korean, but the seems to have stopped,  so I want to start a new translation at my repo.

만약 번역이 이곳에서 아직 진행 중이라면 알려주세요.

Please let me know if the translation is still in progress here.

감사합니다. Thank you.

**Comment by yoongun** [comment]
네!
다른일이 바빠져서 전혀 손 못대고 있어서
번역해 놓은 것들이라도 괜찮으시다면 사용해주세요 😀
