### ISSUE TITLE
translate readme.md

### ISSUE THREAD

**Issue by dolsup** [Gunforge/learn-go-with-tests-ko#7]

**Comment by yoongun** [comment]
Is this issue still on progress?

**Comment by dolsup** [comment]
@cfr2ak revision is needed

**Comment by yoongun** [comment]
@dolsup I think it's better to make other issues for the revision. It took too much time to close the issue compared to its importance.

**Comment by yoongun** [comment]
@dolsup Is there any progress on here? If no, I want to close this issue.

**Comment by dolsup** [comment]
@cfr2ak ok, go ahead
